### PR TITLE
Add generic redirec URI for local dev mode.

### PR DESCRIPTION
**Pull request by zmoore-usgs**

### CODE REVIEW

**Comment by zmoore-usgs** [comment]
Arg seems like it doesn't like just "*". Trying to see if there's a global generic wildcard it will accept or if we'll have to actually set real URLs in each local dev context

**Comment by zmoore-usgs** [comment]
No idea if Travis still actually works for this or not, but I guess we'll see

**Review by cschroed-usgs — APPROVED** [review]
Merge the goods! They are, true to their name, quite good.

**Comment by zmoore-usgs** [comment]
I think I'll just go ahead and merge since I did the docker built locally and it worked fine so this should work and I want to get it out to you guys faster

**Pull request merged**
